name: Enterprise build

on:
  push:
    branches:
      - develop

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  deploy_enterprise:
    name: Deploy enterprise build
    uses: futuredapp/.github/.github/workflows/android-cloud-release-firebaseAppDistribution.yml@main
    with:
      TEST_GRADLE_TASKS: testDevEnterpriseUnitTest
      BUNDLE_GRADLE_TASK: bundleDevEnterprise
      UPLOAD_GRADLE_TASK: appDistributionUploadDevEnterprise
      SIGNING_KEYSTORE_PATH: keystore/debug.jks
      # TODO Verify app distribution groups
      APP_DISTRIBUTION_GROUPS: futured-devs, futured-qa
    secrets:
      # TODO Set up `APP_DISTRIBUTION_SERVICE_ACCOUNT` as plaintext JSON for this GitHub repository
      SIGNING_KEYSTORE_PASSWORD: android
      SIGNING_KEY_ALIAS: androiddebugkey
      SIGNING_KEY_PASSWORD: android
      APP_DISTRIBUTION_SERVICE_ACCOUNT: ${{ secrets.APP_DISTRIBUTION_SERVICE_ACCOUNT }}