name: Check Pull request

on: [ pull_request ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  check:
    uses: futuredapp/.github/.github/workflows/android-cloud-check.yml@main
    with:
      LINT_GRADLE_TASKS: lintCheck
      TEST_GRADLE_TASKS: testDevEnterpriseUnitTest
