name: Release build

on:
  release:
    types: [ published ]

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  deploy_release:
    name: Deploy release build
    uses: futuredapp/.github/.github/workflows/android-cloud-release-googlePlay.yml@main
    with:
      VERSION_NAME: ${{ github.event.release.tag_name }}
      BUNDLE_GRADLE_TASK: bundleProdRelease
      SIGNING_KEYSTORE_PATH: keystore/release.jks
      # TODO This has to be applicationId
      GOOGLE_PLAY_APPLICATION_ID: app.futured.androidprojecttemplate
      GOOGLE_PLAY_WHATSNEW_DIRECTORY: whatsnew
    secrets:
      # TODO Set up `RELEASE_KEYSTORE_PASSWORD` secret for this GitHub repository
      # TODO Set up `RELEASE_KEY_PASSWORD` secret for this GitHub repository
      # TODO Set up `RELEASE_KEY_ALIAS` secret for this GitHub repository
      # TODO Set up `GOOGLE_PLAY_PUBLISH_SERVICE_ACCOUNT` as plaintext JSON for this GitHub repository
      SIGNING_KEYSTORE_PASSWORD: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
      SIGNING_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
      SIGNING_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
      GOOGLE_PLAY_PUBLISH_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_PLAY_PUBLISH_SERVICE_ACCOUNT }}
